name: Test Automation WorkFlow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation Framework with Maven
    
          
          
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadLess=false

    
      
    - name: Upload Test logs 
      if: always()
      uses: actions/upload-artifact@v4.5.0
      with: 
       name: Test logs
       path: logs/

    - name: Upload Test Reports 
      if: always()
      uses: actions/upload-artifact@v4.5.0
      with: 
       name: Test Reports
       path: report.html
     
    - name: Test Execution Status
      run:  echo "Test Execution Completed"

    - name: Copy Report to gh-pages folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l
      

    - name: Deploy 
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.2
      with: 
         folder : public/extent-reports/
         token : ${{ secrets.PAT234 }}
         clean : true

